# Generated by Django 4.1.2 on 2023-01-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
